# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

# Location of the ingested data - we will add on prefixes of 'metadata.tsv.zst',
# 'S/sequences.fasta.zst' etc
ingest_url_prefix: "https://data.nextstrain.org/files/workflows/oropouche/"

strain_id_field: "strain"

filter:
  exclude: "defaults/exclude.txt"
  exclude_where: "abbr_authors=Iani et al."
  min_length:
    L: 3426
    M: 2192
    S: 700

tree:
  method: "iqtree"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_rate: 0.0014

ancestral:
  inference: "joint"

traits:
  columns: "country"

export:
  auspice_config: "defaults/auspice_config.json"
  description: "defaults/description.md"
  segment_metadata_columns:
    - accession_{segment}
    - qc_{segment}
    - length_{segment}
    - date_released_{segment}
    - date_updated_{segment}
